// Autogenerated from Pigeon (v26.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length && a.indexed.every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length &&
        a.entries.every(
          (MapEntry<Object?, Object?> entry) =>
              (b as Map<Object?, Object?>).containsKey(entry.key) && _deepEquals(entry.value, b[entry.key]),
        );
  }
  return a == b;
}

enum UploadApiErrorCode {
  unknown,
  assetNotFound,
  fileNotFound,
  resourceNotFound,
  invalidResource,
  encodingFailed,
  writeFailed,
  notEnoughSpace,
  networkError,
  photosInternalError,
  photosUnknownError,
  noServerUrl,
  noDeviceId,
  noAccessToken,
  interrupted,
  cancelled,
  downloadStalled,
  forceQuit,
  outOfResources,
  backgroundUpdatesDisabled,
  uploadTimeout,
  iCloudRateLimit,
  iCloudThrottled,
}

enum UploadApiGroup { manual, backup, backupLivePhoto, image, video, livePhoto }

enum UploadApiStatus {
  downloadPending,
  downloadQueued,
  downloadFailed,
  uploadPending,
  uploadQueued,
  uploadFailed,
  uploadComplete,
  uploadSkipped,
}

class UploadApiTaskStatus {
  UploadApiTaskStatus({
    required this.id,
    required this.filename,
    required this.group,
    required this.status,
    this.errorCode,
    this.httpStatusCode,
  });

  String id;

  String filename;

  UploadApiGroup group;

  UploadApiStatus status;

  UploadApiErrorCode? errorCode;

  int? httpStatusCode;

  List<Object?> _toList() {
    return <Object?>[id, filename, group, status, errorCode, httpStatusCode];
  }

  Object encode() {
    return _toList();
  }

  static UploadApiTaskStatus decode(Object result) {
    result as List<Object?>;
    return UploadApiTaskStatus(
      id: result[0]! as String,
      filename: result[1]! as String,
      group: result[2]! as UploadApiGroup,
      status: result[3]! as UploadApiStatus,
      errorCode: result[4] as UploadApiErrorCode?,
      httpStatusCode: result[5] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UploadApiTaskStatus || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class UploadApiTaskProgress {
  UploadApiTaskProgress({required this.id, required this.progress, this.speed, this.totalBytes});

  String id;

  double progress;

  double? speed;

  int? totalBytes;

  List<Object?> _toList() {
    return <Object?>[id, progress, speed, totalBytes];
  }

  Object encode() {
    return _toList();
  }

  static UploadApiTaskProgress decode(Object result) {
    result as List<Object?>;
    return UploadApiTaskProgress(
      id: result[0]! as String,
      progress: result[1]! as double,
      speed: result[2] as double?,
      totalBytes: result[3] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UploadApiTaskProgress || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is UploadApiErrorCode) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is UploadApiGroup) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is UploadApiStatus) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is UploadApiTaskStatus) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is UploadApiTaskProgress) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : UploadApiErrorCode.values[value];
      case 130:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : UploadApiGroup.values[value];
      case 131:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : UploadApiStatus.values[value];
      case 132:
        return UploadApiTaskStatus.decode(readValue(buffer)!);
      case 133:
        return UploadApiTaskProgress.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class UploadApi {
  /// Constructor for [UploadApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  UploadApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
    : pigeonVar_binaryMessenger = binaryMessenger,
      pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> initialize() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.immich_mobile.UploadApi.initialize$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> refresh() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.immich_mobile.UploadApi.refresh$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> cancelAll() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.immich_mobile.UploadApi.cancelAll$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> enqueue(List<String> localIds) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.immich_mobile.UploadApi.enqueue$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[localIds]);
    final List<Object?>? pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class UploadFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onTaskProgress(UploadApiTaskProgress progress);

  void onTaskStatus(UploadApiTaskStatus status);

  static void setUp(UploadFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.immich_mobile.UploadFlutterApi.onTaskProgress$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.immich_mobile.UploadFlutterApi.onTaskProgress was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final UploadApiTaskProgress? arg_progress = (args[0] as UploadApiTaskProgress?);
          assert(
            arg_progress != null,
            'Argument for dev.flutter.pigeon.immich_mobile.UploadFlutterApi.onTaskProgress was null, expected non-null UploadApiTaskProgress.',
          );
          try {
            api.onTaskProgress(arg_progress!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.immich_mobile.UploadFlutterApi.onTaskStatus$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.immich_mobile.UploadFlutterApi.onTaskStatus was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final UploadApiTaskStatus? arg_status = (args[0] as UploadApiTaskStatus?);
          assert(
            arg_status != null,
            'Argument for dev.flutter.pigeon.immich_mobile.UploadFlutterApi.onTaskStatus was null, expected non-null UploadApiTaskStatus.',
          );
          try {
            api.onTaskStatus(arg_status!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
